"""init

Revision ID: 39f0d57c9795
Revises: 
Create Date: 2026-03-25 18:36:06.415135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '39f0d57c9795'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role'), server_default='USER', nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vaults',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('categories',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('vault_uid', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monthly_limit', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['vault_uid'], ['vaults.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_categories_vault_uid'), 'categories', ['vault_uid'], unique=False)
    op.create_table('users_to_vaults',
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('vault_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['vault_uid'], ['vaults.uid'], ),
    sa.PrimaryKeyConstraint('user_uid', 'vault_uid')
    )
    op.create_index(op.f('ix_users_to_vaults_vault_uid'), 'users_to_vaults', ['vault_uid'], unique=False)
    op.create_table('transactions',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('category_uid', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['category_uid'], ['categories.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_users_to_vaults_vault_uid'), table_name='users_to_vaults')
    op.drop_table('users_to_vaults')
    op.drop_index(op.f('ix_categories_vault_uid'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('vaults')
    op.drop_table('users')
    # ### end Alembic commands ###
