"""Fix UserToVault

Revision ID: cf8f744f042f
Revises: 39f0d57c9795
Create Date: 2026-03-27 11:04:44.697875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf8f744f042f'
down_revision: Union[str, Sequence[str], None] = '39f0d57c9795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.add_column('users_to_vaults', sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role'), server_default='USER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_to_vaults', 'role')
    op.add_column('users', sa.Column('role', postgresql.ENUM('ADMIN', 'USER', name='user_role'), server_default=sa.text("'USER'::user_role"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
